Bai3/Models/Banner.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
    }
}

Bai3/Models/Menu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Alias { get; set; }
    }
}

Bai3/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bai3Entities : DbContext
    {
        public Bai3Entities()
            : base("name=Bai3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
    }
}

Bai3/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\DELL\source\repos\Bai3\Bai3\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Bai3/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Bai3/Models/sysdiagrams.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagrams
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}

Bai3/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bai3.Models;

namespace Bai3.Controllers
{
    public class BannerController : Controller
    {
        Bai3Entities db = new Bai3Entities();
        // GET: Banner
       
            public ActionResult Index()
            {
                return View();
            }
            public ActionResult HeaderBanner()
            {
                var headerBanner = db.Banner.Where(c => c.Name == "Header").FirstOrDefault();
                return PartialView(headerBanner);
            }
            public ActionResult LeftBanner()
            {
                var leftBanner = db.Banner.Where(c => c.Name == "Left").FirstOrDefault();
                return PartialView(leftBanner);
            }
            public ActionResult RightBanner()
            {
                var rightBanner = db.Banner.Where(c => c.Name == "Right").FirstOrDefault();
                return PartialView(rightBanner);
            }
        }
   }

Bai3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Bai3/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bai3.Models;
namespace Bai3.Controllers
{
    public class MenuController : Controller
    {
        Bai3Entities db = new Bai3Entities();
        // GET: Menu
        public ActionResult Index()
        {
            var menus = db.Menu;
            return PartialView(menus);
        }
    }
}

Bai3/Views/Banner/HeaderBanner.cshtml
@model Bai3.Models.Banner
    <div>
        <img style="display:block;margin-left:auto;margin-right:auto;max-height:150px" src="@Model.URL" alt="Alternate Text"/>
    </div>

Bai3/Views/Banner/LeftBanner.cshtml
@model Bai3.Models.Banner
<div>
    <img style="float:left;max-height:800px; width:100%" src="@Model.URL" alt="Alternate Text" />
</div>

Bai3/Views/Banner/RightBanner.cshtml
@model Bai3.Models.Banner
<div>
    <img style="float:right;max-height:800px; width:100%" src="@Model.URL" alt="Alternate Text" />
</div>

Bai3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Bai3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Bai3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



    <div class="row">
        <div class="col-md-2">
            @{ Html.RenderAction("LeftBanner", "Banner");}
        </div>
        <div class="col-md-2">
            <h2></h2>

        </div>
        <div class="col-md-2">
            <h2></h2>
            <p></p>
            <p></p>
        </div>
        <div class="col-md-2">
            <h2>LAB3 TMĐT </h2>
            <p></p>
            <p></p>
        </div>
        <div class="col-md-2">
            <h2></h2>
            <p></p>
            <p></p>
        </div>
        <div class="col-md-2">
            @{ Html.RenderAction("RightBanner", "Banner");}
        </div>
    </div>

Bai3/Views/Menu/Index.cshtml
@model IEnumerable<Bai3.Models.Menu>
@{
    ViewBag.Title = "Index";
}

<nav>

    <ul>

        <li>

            <a href="#">ĐIỆN THOẠI</a>

            <input type="checkbox" id="btn-2">
            <ul>

                @foreach (var item in Model.Where(c => c.ParentID == null).OrderBy(c => c.SortOrder))
                {
                    <li>
                        <a class="dropdown-item" href="@item.Alias" style="width:150%">
                            @item.Name
                        </a>

                        @RenderMenuItem(Model.ToList(), item, item.Alias)
                    </li>

                }


            </ul>
            
          
        </li>
       
    </ul>
</nav>


@section scripts{
    <script>
        $('.icon').click(function () {
            $('span').toggleClass("cancel");
        });
    </script>

}

@helper RenderMenuItem(List<Bai3.Models.Menu> list, Bai3.Models.Menu itemMenu, string alias)
{


    <ul style="">
        @foreach (var item in list.Where(c => c.ParentID == itemMenu.ID).OrderBy(c => c.SortOrder))
        {
            <li>

                <label for="btn-3" class="show">+</label>
                
                <input type="checkbox" id="btn-2">
                <a href="@alias/@item.Alias" style="width:100%">
                    @item.Name
                </a>
                @RenderMenuItem(list, item, item.Alias)
            </li>
        }
    </ul>
}

Bai3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tuần 3 TMĐT CSS HTML</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <link href="~/Content/StyleSheet1.css" rel="stylesheet" />
</head>
<body>
    <div>
        @{ Html.RenderAction("HeaderBanner", "Banner");}
    </div>
   

    <div class="navbar navbar-inverse ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Danh Sách Các Menu : ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    @{ Html.RenderAction("Index", "Menu");}

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>    
            <a href="#" style="width:200%">BAI3 TMĐT </a>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>